meta_product_name: "Crypto4you"
meta_title: "Crypto4you - Organize and structure your crypto investments"
meta_description: "A simple and effective way to highlight your crypto investments.
We help you to have more transparency over your taxes and to
simply store your trades in a convenient way to get a great
review over your trades and taxes."
meta_image: "image.png" # should exist in `app/assets/images/`
